[[main]]
  name = "Posts"
  url = ""
  weight = -110

[[main]]
  name = "Archive"
  url = "post/archive/"
  weight = -109

[[main]]
  name = "About"
  url = "about/"
  weight = -107

# social menu links
[[social]]
  name = "linkedin"
  weight = 3
  url = "https://www.linkedin.com/in/philippe-assouline/"
